<?php

namespace app\admin\controller;

use app\common\model\Category;
use think\Controller;

class Article extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    //文章首页
    public function index(){
        $article_data = $this->db->getAll();
        $this->assign('article_data',$article_data);
        return $this->fetch();
    }

    //添加文章
    public function store(){
        if(request()->isPost()){
            $res = $this->db->store(input('post.'));
            if($res['valid']==1){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }else {
            //1.获取文章分类信息
            $cate_list = (new Category())->getAll();
            $this->assign('cate_list', $cate_list);
            //2.获取标签数据
            $tag_list = db('tag')->select();
            $this->assign('tag_list', $tag_list);
            return $this->fetch();
        }
    }

}
