<?php

namespace app\admin\controller;

use think\Controller;

class Category extends Controller
{
    protected $db;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Category();
    }

    //栏目管理
    public function index(){
        return $this->fetch();
    }

    //添加栏目
    public function store()
    {
        if(request()->isPost()){
             $res = $this->db->store(input('post.'));
             if($res['valid']!=0){
                 $this->success($res['msg'],'index');
             }else{
                 $this->error($res['msg']);
             }
        }else{
            return $this->fetch();
        }
    }
}
