<?php

namespace app\admin\controller;

use think\Controller;

class Tag extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Tag();
    }

    //标签管理
    public function index()
    {
        $list = db('Tag')->paginate(5);
        $this->assign('list',$list);
        return $this->fetch();
    }
    //添加标签
    public function store()
    {
        if(request()->isPost()){
            $res = $this->db->store(input('post.'));
            if($res['valid']==1){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg']);
            }
        }else{
            return $this->fetch();
        }
    }
}
